name: API Docs

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Generate API documentation
        run: npm run generate-docs
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: docs
          commit_message: "Signed-off-by: Lance Ball <lball@redhat.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
